We will unit test the job run by validating the percentage count generated by Below query results with the catalogued table generated by the Glue Job



Expected Result

with counts_table as (select distinct count(1) as count_val, 'Y' as auto_suggested
			from autosuggest_db.autosuggest_table a inner join user_search_db.user_search_data_table b
			  on a.autosuggest_phrase = b.user_search_phrase
		       where date(b.request_timestamp)= '01012022'
		     UNION ALL
			select distinct count(1) as count_val ,'N' as auto_suggested
			 from user_search_db.user_search_data_table c
			 where Date(c.request_timestamp)= '01012022'),
total_table as (  SELECT sum(case when auto_suggested = 'Y' then count_val else 0 end ) as auto_suggest_count ,
			 Sum(count_val) as total
    		    from counts_table)
Select  total as total_search_request,
	(cast(auto_suggest_count as decimal)*100/cast(total as decimal)) as Auto_suggest_percent
  from total_table;


Actual Result

Select * from user_search_result_db.curated_output where request_date = '01012022'


